# Generated by Django 2.1.5 on 2019-11-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookARI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('n_characters', models.IntegerField()),
                ('n_words', models.IntegerField()),
                ('n_sentences', models.IntegerField()),
                ('ari', models.IntegerField()),
                ('age_range', models.CharField(max_length=50)),
                ('grade_level', models.CharField(max_length=50)),
            ],
        ),
    ]
